In [26]:
import sys
assert sys.version_info >= (3, 5)
# Python ≥3.5 is required
import sklearn
assert sklearn.__version__ >= "0.20"
import numpy as np
import os
import tarfile
import urllib
import pandas as pd
import urllib.request
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve
from sklearn import preprocessing
from sklearn import metrics
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import json
from pathlib import Path

In [27]:
data = pd.read_csv("02-19-2023.csv")

In [28]:
data

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2023-02-20 04:21:05,33.939110,67.709953,209107,7896,NaN,NaN,Afghanistan,537.158776,3.776057
1,NaN,NaN,NaN,Albania,2023-02-20 04:21:05,41.153300,20.168300,334314,3596,NaN,NaN,Albania,11616.999097,1.075635
2,NaN,NaN,NaN,Algeria,2023-02-20 04:21:05,28.033900,1.659600,271425,6881,NaN,NaN,Algeria,618.970454,2.535139
3,NaN,NaN,NaN,Andorra,2023-02-20 04:21:05,42.506300,1.521800,47866,165,NaN,NaN,Andorra,61950.430337,0.344712
4,NaN,NaN,NaN,Angola,2023-02-20 04:21:05,-11.202700,17.873900,105184,1931,NaN,NaN,Angola,320.036336,1.835831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4011,NaN,NaN,NaN,West Bank and Gaza,2023-02-20 04:21:05,31.952200,35.233200,703228,5708,NaN,NaN,West Bank and Gaza,13784.956961,0.811686
4012,NaN,NaN,NaN,Winter Olympics 2022,2023-02-20 04:21:05,39.904200,116.407400,535,0,NaN,NaN,Winter Olympics 2022,NaN,0.000000
4013,NaN,NaN,NaN,Yemen,2023-02-20 04:21:05,15.552727,48.516388,11945,2159,NaN,NaN,Yemen,40.048994,18.074508
4014,NaN,NaN,NaN,Zambia,2023-02-20 04:21:05,-13.133897,27.849332,342317,4051,NaN,NaN,Zambia,1862.042098,1.183406
4015,NaN,NaN,NaN,Zimbabwe,2023-02-20 04:21:05,-19.015438,29.154857,263642,5662,NaN,NaN,Zimbabwe,1773.822882,2.147609

In [29]:
geoJSONDict = {

  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "features": []
}

In [69]:
# incident rate = (Cases/population)*100,000
# population = (Cases*100,000)/incident rate
data["Population"] = (data["Confirmed"] * 100000)/data["Incident_Rate"]
data["Cases_per_1000"] = (data["Confirmed"]/data['Population'])*1000
#data["Incident_Rate"] = (data["Deaths"] / data["Population"])* 1000
data["Case_Fatality_Ratio"] = (data["Case_Fatality_Ratio"]*100).round()
data = data[data['Confirmed'] >= data['Deaths']]
data = data.sort_values(by='Incident_Rate', ascending=False)
data.head(50)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Population,Cases_per_1000
0,NaN,NaN,Faroe Islands,Denmark,2023-02-20 04:21:05,61.892600,-6.911800,34658.0,28.0,NaN,NaN,"Faroe Islands, Denmark",70926.020669,800.0,48865.0,709.260207
1,NaN,NaN,NaN,San Marino,2023-02-20 04:21:05,43.942400,12.457800,23521.0,122.0,NaN,NaN,San Marino,69305.792916,5200.0,33938.0,693.057929
2,NaN,NaN,NaN,Austria,2023-02-20 04:21:05,47.516200,14.550100,5863481.0,21820.0,NaN,NaN,Austria,65103.493072,3700.0,9006400.0,651.034931
3,NaN,NaN,NaN,Slovenia,2023-02-20 04:21:05,46.151200,14.995500,1325505.0,7067.0,NaN,NaN,Slovenia,63758.939686,5300.0,2078932.0,637.589397
4,NaN,NaN,NaN,Brunei,2023-02-20 04:21:05,4.535300,114.727700,277441.0,225.0,NaN,NaN,Brunei,63417.549939,800.0,437483.0,634.175499
5,NaN,NaN,NaN,Andorra,2023-02-20 04:21:05,42.506300,1.521800,47866.0,165.0,NaN,NaN,Andorra,61950.430337,3400.0,77265.0,619.504303
6,NaN,NaN,NaN,Iceland,2023-02-20 04:21:05,64.963100,-19.020800,208921.0,211.0,NaN,NaN,Iceland,61222.271062,1000.0,341250.0,612.222711
7,NaN,NaN,Martinique,France,2023-02-20 04:21:05,14.641500,-61.024200,228756.0,1091.0,NaN,NaN,"Martinique, France",60958.522644,4800.0,375265.0,609.585226
8,NaN,NaN,Jersey,United Kingdom,2023-02-20 04:21:05,49.213800,-2.135800,66391.0,161.0,NaN,NaN,"Jersey, United Kingdom",60741.994511,2400.0,109300.0,607.419945
9,NaN,NaN,Gibraltar,United Kingdom,2023-02-20 04:21:05,36.140800,-5.353600,20414.0,111.0,NaN,NaN,"Gibraltar, United Kingdom",60591.849455,5400.0,33691.0,605.918495
10,NaN,NaN,Saint Pierre and Miquelon,France,2023-02-20 04:21:05,46.885200,-56.315900,3452.0,2.0,NaN,NaN,"Saint Pierre and Miquelon, France",59568.593615,600.0,5795.0,595.685936
11,NaN,NaN,NaN,"Korea, South",2023-02-20 04:21:05,35.907757,127.766922,30433895.0,33865.0,NaN,NaN,"Korea, South",59360.990792,1100.0,51269183.0,593.609908
12,NaN,NaN,NaN,France,2023-02-20 04:21:05,46.227600,2.213700,38539362.0,161090.0,NaN,NaN,France,59042.880978,4200.0,65273512.0,590.428810
13,NaN,NaN,NaN,Denmark,2023-02-20 04:21:05,56.263900,9.501800,3402118.0,8228.0,NaN,NaN,Denmark,58736.166533,2400.0,5792203.0,587.361665
14,NaN,NaN,NaN,Liechtenstein,2023-02-20 04:21:05,47.140000,9.550000,21387.0,89.0,NaN,NaN,Liechtenstein,56079.397960,4200.0,38137.0,560.793980
15,NaN,NaN,Falkland Islands (Malvinas),United Kingdom,2023-02-20 04:21:05,-51.796300,-59.523600,1930.0,0.0,NaN,NaN,"Falkland Islands (Malvinas), United Kingdom",55412.001148,0.0,3483.0,554.120011
16,NaN,NaN,NaN,Israel,2023-02-20 04:21:05,31.046051,34.851612,4794287.0,12250.0,NaN,NaN,Israel,55389.801747,2600.0,8655541.0,553.898017
17,NaN,NaN,Guernsey,United Kingdom,2023-02-20 04:21:05,49.448196,-2.589490,34867.0,66.0,NaN,NaN,"Guernsey, United Kingdom",55344.444444,1900.0,63000.0,553.444444
18,NaN,NaN,Reunion,France,2023-02-20 04:21:05,-21.115100,55.536400,494595.0,921.0,NaN,NaN,"Reunion, France",55243.000174,1900.0,895308.0,552.430002
19,NaN,NaN,P.A. Bolzano,Italy,2023-02-20 04:21:05,46.499335,11.356624,293048.0,1609.0,NaN,NaN,"P.A. Bolzano, Italy",55051.303920,5500.0,532318.0,550.513039
20,NaN,NaN,Saint Barthelemy,France,2023-02-20 04:21:05,17.900000,-62.833300,5431.0,6.0,NaN,NaN,"Saint Barthelemy, France",54941.831057,1100.0,9885.0,549.418311
21,NaN,NaN,Veneto,Italy,2023-02-20 04:21:05,45.434905,12.338452,2685547.0,16626.0,NaN,NaN,"Veneto, Italy",54741.682080,6200.0,4905854.0,547.416821
22,NaN,NaN,NaN,Portugal,2023-02-20 04:21:05,39.399900,-8.224500,5566708.0,26117.0,NaN,NaN,Portugal,54593.193665,4700.0,10196707.0,545.931937
23,NaN,NaN,Australian Capital Territory,Australia,2023-02-20 04:21:05,-35.473500,149.012400,231529.0,224.0,NaN,NaN,"Australian Capital Territory, Australia",54082.924550,1000.0,428100.0,540.829246
24,NaN,NaN,NaN,Cyprus,2023-02-20 04:21:05,35.126400,33.429900,647031.0,1297.0,NaN,NaN,Cyprus,53590.516838,2000.0,1207361.0,535.905168
25,NaN,NaN,Tasmania,Australia,2023-02-20 04:21:05,-42.882100,147.327200,285299.0,250.0,NaN,NaN,"Tasmania, Australia",53277.124183,900.0,535500.0,532.771242
26,NaN,NaN,NaN,Greece,2023-02-20 04:21:05,39.074200,21.824300,5548487.0,34779.0,NaN,NaN,Greece,53232.823464,6300.0,10423056.0,532.328235
27,NaN,NaN,Utrecht,Netherlands,2023-02-20 04:21:05,52.084251,5.163824,707455.0,1581.0,NaN,NaN,"Utrecht, Netherlands",52217.098183,2200.0,1354834.0,522.170982
28,NaN,NaN,NaN,Latvia,2023-02-20 04:21:05,56.879600,24.603200,975767.0,6255.0,NaN,NaN,Latvia,51731.839962,6400.0,1886202.0,517.318400
29,NaN,NaN,NaN,Seychelles,2023-02-20 04:21:05,-4.679600,55.492000,50665.0,172.0,NaN,NaN,Seychelles,51520.235916,3400.0,98340.0,515.202359
30,NaN,NaN,Overijssel,Netherlands,2023-02-20 04:21:05,52.444558,6.441722,598629.0,1459.0,NaN,NaN,"Overijssel, Netherlands",51499.131973,2400.0,1162406.0,514.991320
31,NaN,NaN,Bayern,Germany,2023-02-20 04:21:05,48.790400,11.497900,6704634.0,28323.0,NaN,NaN,"Bayern, Germany",51271.522884,4200.0,13076721.0,512.715229
32,NaN,NaN,NaN,Switzerland,2023-02-20 04:21:05,46.818200,8.227500,4409828.0,14202.0,NaN,NaN,Switzerland,50953.467848,3200.0,8654618.0,509.534678
33,NaN,NaN,Noord-Brabant,Netherlands,2023-02-20 04:21:05,51.561174,5.184942,1303291.0,3783.0,NaN,NaN,"Noord-Brabant, Netherlands",50851.107413,2900.0,2562955.0,508.511074
34,NaN,NaN,Limburg,Netherlands,2023-02-20 04:21:05,51.209227,5.933870,565521.0,2209.0,NaN,NaN,"Limburg, Netherlands",50619.449857,3900.0,1117201.0,506.194499
35,NaN,NaN,NaN,Luxembourg,2023-02-20 04:21:05,49.815300,6.129600,315778.0,1214.0,NaN,NaN,Luxembourg,50445.703989,3800.0,625976.0,504.457040
36,NaN,NaN,Gelderland,Netherlands,2023-02-20 04:21:05,52.061738,5.939114,1051844.0,2952.0,NaN,NaN,"Gelderland, Netherlands",50425.129629,2800.0,2085952.0,504.251296
37,NaN,NaN,Guadeloupe,France,2023-02-20 04:21:05,16.265000,-61.551000,201704.0,1010.0,NaN,NaN,"Guadeloupe, France",50409.994827,5000.0,400127.0,504.099948
38,NaN,NaN,South Australia,Australia,2023-02-20 04:21:05,-34.928500,138.600700,878436.0,1322.0,NaN,NaN,"South Australia, Australia",50010.589240,1500.0,1756500.0,500.105892
39,NaN,NaN,Abruzzo,Italy,2023-02-20 04:21:05,42.351222,13.398438,650357.0,3913.0,NaN,NaN,"Abruzzo, Italy",49585.766785,6000.0,1311580.0,495.857668
40,NaN,NaN,Umbria,Italy,2023-02-20 04:21:05,43.106758,12.388247,437013.0,2429.0,NaN,NaN,"Umbria, Italy",49547.116546,5600.0,882015.0,495.471165
41,NaN,NaN,Saarland,Germany,2023-02-20 04:21:05,49.396400,7.023000,487632.0,2111.0,NaN,NaN,"Saarland, Germany",49230.446165,4300.0,990509.0,492.304462
42,NaN,NaN,Noord-Holland,Netherlands,2023-02-20 04:21:05,52.600906,4.918688,1412677.0,3508.0,NaN,NaN,"Noord-Holland, Netherlands",49059.342038,2500.0,2879527.0,490.593420
43,NaN,NaN,NaN,Slovakia,2023-02-20 04:21:05,48.669000,19.699000,2663604.0,20996.0,NaN,NaN,Slovakia,49010.950350,7900.0,5434712.0,490.109504
44,NaN,NaN,Western Australia,Australia,2023-02-20 04:21:05,-31.950500,115.860500,1288808.0,942.0,NaN,NaN,"Western Australia, Australia",48992.929370,700.0,2630600.0,489.929294
45,NaN,NaN,Zuid-Holland,Netherlands,2023-02-20 04:21:05,51.937835,4.462114,1801509.0,5299.0,NaN,NaN,"Zuid-Holland, Netherlands",48575.267426,2900.0,3708696.0,485.752674
46,NaN,NaN,Niedersachsen,Germany,2023-02-20 04:21:05,52.636700,9.845100,3839209.0,13454.0,NaN,NaN,"Niedersachsen, Germany",48095.634322,3500.0,7982448.0,480.956343
47,NaN,NaN,New South Wales,Australia,2023-02-20 04:21:05,-33.868800,151.209300,3894431.0,6417.0,NaN,NaN,"New South Wales, Australia",47972.788864,1600.0,8118000.0,479.727889
48,NaN,NaN,Cayman Islands,United Kingdom,2023-02-20 04:21:05,19.313300,-81.254600,31472.0,37.0,NaN,NaN,"Cayman Islands, United Kingdom",47888.009738,1200.0,65720.0,478.880097
49,NaN,NaN,NaN,Lithuania,2023-02-20 04:21:05,55.169400,23.881300,1301860.0,9570.0,NaN,NaN,Lithuania,47822.220328,7400.0,2722291.0,478.222203

In [70]:
data.loc[data['Country_Region']=='United Arab Emirates']

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Population,Cases_per_1000
449,NaN,NaN,NaN,United Arab Emirates,2023-02-20 04:21:05,23.424076,53.847818,1051079.0,2349.0,NaN,NaN,United Arab Emirates,10627.264822,2200.0,9890400.0,106.272648

In [32]:
data["Deaths"].sum()

6854432

In [33]:
data["Case_Fatality_Ratio"].sum()

574322.0

In [34]:
data["Incident_Rate"].sum()

111222738.00460437

In [35]:
us_data = data.loc[data['Country_Region']=='US']
data = data[data['Country_Region']!='US']

In [36]:
us_data

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Population
3495,48301.0,Loving,Texas,US,2023-02-20 04:21:05,31.849476,-103.581857,396,1,NaN,NaN,"Loving, Texas, US",234319.526627,25.0,169.0
755,2068.0,Denali,Alaska,US,2023-02-20 04:21:05,63.672640,-150.007611,1801,2,NaN,NaN,"Denali, Alaska, US",85884.597043,11.0,2097.0
765,2180.0,Nome,Alaska,US,2023-02-20 04:21:05,64.903207,-164.035380,7547,7,NaN,NaN,"Nome, Alaska, US",75439.824070,9.0,10004.0
767,2188.0,Northwest Arctic,Alaska,US,2023-02-20 04:21:05,67.049192,-159.750395,5747,22,NaN,NaN,"Northwest Arctic, Alaska, US",75410.051174,38.0,7621.0
3468,48247.0,Jim Hogg,Texas,US,2023-02-20 04:21:05,27.044539,-98.696819,3792,23,NaN,NaN,"Jim Hogg, Texas, US",72923.076923,61.0,5200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3753,90051.0,Unassigned,Virginia,US,2020-12-21 13:27:30,NaN,NaN,0,0,NaN,NaN,"Unassigned, Virginia, US",NaN,NaN,NaN
3798,90053.0,Unassigned,Washington,US,2023-02-20 04:21:05,NaN,NaN,3303,6,NaN,NaN,"Unassigned, Washington, US",NaN,18.0,NaN
3852,90054.0,Unassigned,West Virginia,US,2021-07-31 23:21:38,NaN,NaN,0,0,NaN,NaN,"Unassigned, West Virginia, US",NaN,NaN,NaN
3922,90055.0,Unassigned,Wisconsin,US,2023-02-20 04:21:05,NaN,NaN,0,0,NaN,NaN,"Unassigned, Wisconsin, US",NaN,NaN,NaN
3954,90056.0,Unassigned,Wyoming,US,2023-01-08 23:21:00,NaN,NaN,0,0,NaN,NaN,"Unassigned, Wyoming, US",NaN,NaN,NaN

In [37]:
country_wise_data = pd.DataFrame()

In [38]:
#data struct to store states
# for every state in us_data: 
# get average of Case_Fatality_Ratio, median of lat and long, country
# insert row into data

countries =  data.Country_Region.values.tolist()
countries = list(dict.fromkeys(countries))

for country in countries:
    tempDf = data.loc[data['Country_Region']==country]
    countryDf = tempDf.groupby('Country_Region', as_index=False).Deaths.sum()
    case_fatality = tempDf.groupby('Country_Region', as_index=False).Case_Fatality_Ratio.median().iloc[0]['Case_Fatality_Ratio']
    lat = tempDf.groupby('Country_Region', as_index=False).Lat.median().iloc[0]['Lat']
    long = tempDf.groupby('Country_Region', as_index=False).Long_.median().iloc[0]['Long_']
  #  country = "US"
    countryDf["Lat"] = lat
    countryDf["Long_"] = long
    countryDf["Case_Fatality_Ratio"] = case_fatality
   # stateDf["Country_Region"] = country
    countryDf
    country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1714300058.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  country_wise_data = country_wise_data.append(countryDf, ignore_index=True)

In [39]:
country_wise_data_scaled = country_wise_data
country_wise_data.sort_values(by='Case_Fatality_Ratio', ascending=False).head(100)

        Country_Region  Deaths        Lat      Long_  Case_Fatality_Ratio
196         MS Zaandam       2        NaN        NaN               2222.0
192              Yemen    2159  15.552727  48.516388               1807.0
185              Sudan    5011  12.862800  30.217600                786.0
171              Syria    3164  34.802075  38.996815                551.0
181            Somalia    1361   5.152149  46.199616                498.0
..                 ...     ...        ...        ...                  ...
70               India  530761  23.780432  78.942140                107.0
139          Venezuela    5852   6.423800 -66.589700                106.0
147  Equatorial Guinea     183   1.650800  10.267900                106.0
35               Chile   64085 -35.046900 -71.475800                104.0
119               Iraq   25375  33.223191  43.679291                103.0

[100 rows x 5 columns]

In [40]:
country_wise_data.quantile(0.25)

Deaths                 380.0000
Lat                      3.9193
Long_                   -8.2245
Case_Fatality_Ratio     47.5000
Name: 0.25, dtype: float64

In [41]:
country_wise_data.median()

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\2100298474.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  country_wise_data.median()

Deaths                 3164.0000
Lat                      17.0608
Long_                    20.9394
Case_Fatality_Ratio     103.0000
dtype: float64

In [42]:
country_wise_data.quantile(0.75).round()

Deaths                 18506.0
Lat                       39.0
Long_                     47.0
Case_Fatality_Ratio      187.0
Name: 0.75, dtype: float64

In [43]:
country_wise_data_scaled["Case_Fatality_Ratio"] = country_wise_data_scaled["Case_Fatality_Ratio"]/2.28
country_wise_data_scaled["Deaths"] = country_wise_data_scaled["Deaths"]/2.28
country_wise_data.sort_values(by='Deaths', ascending=False).tail(100)

,Country_Region,Deaths,Lat,Long_,Case_Fatality_Ratio
171,Syria,1387.719298,34.802075,38.996815,241.666667
186,Nigeria,1383.771930,9.082000,8.675300,51.754386
151,Cambodia,1340.350877,11.550000,104.916700,96.491228
131,Kyrgyzstan,1311.842105,41.204380,74.766098,63.596491
27,Estonia,1283.333333,58.595300,25.013600,21.052632
...,...,...,...,...,...
60,Tuvalu,0.000000,-7.109500,177.649300,0.000000
194,Antarctica,0.000000,-71.949900,23.347000,0.000000
128,Holy See,0.000000,41.902900,12.453400,0.000000
197,Summer Olympics 2020,0.000000,35.649100,139.773700,0.000000
198,Winter Olympics 2022,0.000000,39.904200,116.407400,0.000000

In [44]:
country_wise_data_scaled.quantile(0.25)

Deaths                 166.666667
Lat                      3.919300
Long_                   -8.224500
Case_Fatality_Ratio     20.833333
Name: 0.25, dtype: float64

In [45]:
country_wise_data_scaled.median()

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\2592085398.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  country_wise_data_scaled.median()

Deaths                 1387.719298
Lat                      17.060800
Long_                    20.939400
Case_Fatality_Ratio      45.175439
dtype: float64

In [46]:
country_wise_data_scaled.quantile(0.75).round()

Deaths                 8117.0
Lat                      39.0
Long_                    47.0
Case_Fatality_Ratio      82.0
Name: 0.75, dtype: float64

In [47]:
#data struct to store states
# for every state in us_data: 
# get average of Case_Fatality_Ratio, median of lat and long, country
# insert row into data

states =  us_data.Province_State.values.tolist()
states = list(dict.fromkeys(states))

for state in states:
    tempDf = us_data.loc[us_data['Province_State']==state]
    stateDf = tempDf.groupby('Province_State', as_index=False).Case_Fatality_Ratio.mean()
    lat = tempDf.groupby('Province_State', as_index=False).Lat.median().iloc[0]['Lat']
    long = tempDf.groupby('Province_State', as_index=False).Long_.median().iloc[0]['Long_']
  #  country = "US"
    stateDf["Lat"] = lat
    stateDf["Long_"] = long
   # stateDf["Country_Region"] = country
    stateDf
    data = data.append(stateDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_5228\1471081376.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)

In [48]:
clean_data_case_fatality = data.drop(['FIPS', 'Admin2','Province_State','Country_Region','Last_Update','Incident_Rate','Recovered','Active','Combined_Key','Deaths','Confirmed'], axis=1)
clean_data_case_fatality = clean_data_case_fatality.dropna()
clean_data_case_fatality.loc[~(clean_data_case_fatality==0.0).all(axis=1)]
clean_data_case_fatality = clean_data_case_fatality.sort_values(by='Case_Fatality_Ratio', ascending=False)
clean_data_case_fatality.head(50)

           Lat       Long_  Case_Fatality_Ratio   Population
688  15.552727   48.516388               1807.0   29825968.0
605  19.566500 -101.706800                789.0    4825401.0
675  12.862800   30.217600                786.0   43849269.0
588  19.041400  -98.206300                764.0    6604451.0
599  19.173800  -96.134200                731.0    8539862.0
464  -6.353049  -79.824113                730.0    1310800.0
485  -5.133361  -80.335861                729.0    2048000.0
505  -9.621718  -73.444929                720.0     589100.0
558  30.840600 -115.283800                719.0    3634868.0
392 -14.235097  -75.574821                700.0     975200.0
537  -4.124847  -74.424115                691.0    1027600.0
573  20.091100  -98.762400                684.0    3086414.0
584  20.659500 -103.349400                683.0    8409693.0
570  19.496900  -99.723300                654.0   17427790.0
356 -11.954609  -77.136042                639.0    1129900.0
677  30.975600  112.270700                626.0   59170000.0
534 -14.995827  -69.922726                619.0    1238000.0
478  -7.921390  -78.370238                606.0    2016800.0
562  28.633000 -106.069100                594.0    3801487.0
590  17.439200  -99.545100                579.0    3657048.0
556  18.681300  -99.101300                553.0    2044058.0
657  34.802075   38.996815                551.0   17500657.0
549  25.172100 -107.479500                549.0    3156674.0
567  19.313900  -98.240400                526.0    1380011.0
564  19.830100  -90.534900                520.0    1000617.0
391  -3.857496  -80.545255                517.0     251500.0
528  29.297200 -110.330900                515.0    3074745.0
670   5.152149   46.199616                498.0   15893219.0
533  20.709900  -89.094300                491.0    2259098.0
501  -9.421676  -76.040642                490.0     760300.0
429 -11.541783  -74.876968                490.0    1361500.0
548  27.058700 -101.706800                485.0    3218720.0
646  26.820553   30.802498                481.0  102334403.0
555  22.770900 -102.583200                480.0    1666426.0
388  -9.407125  -77.671795                464.0    1180600.0
504  -7.039531  -76.729127                462.0     899600.0
288 -11.766533  -76.604498                458.0   10628500.0
554  24.266900  -98.836300                456.0    3650602.0
565  24.559300 -104.658800                454.0    1868996.0
544  21.751400 -104.845500                432.0    1288571.0
495 -14.091648  -74.083440                432.0     668200.0
631  16.756900  -93.129200                431.0    5730367.0
496 -13.023888  -75.002770                430.0     365300.0
481  55.425992   47.084943                428.0    1231117.0
413 -11.972699  -70.531720                416.0     173800.0
545  21.019000 -101.257400                416.0    6228175.0
494   7.946300  -72.898800                415.0    1491689.0
507  -6.430284  -78.745596                411.0    1453700.0
576  17.073200  -96.726600                409.0    4143593.0
531   0.869900  -73.841900                405.0     401489.0

In [49]:
clean_data_deaths = data.drop(['FIPS', 'Admin2','Province_State','Country_Region','Last_Update','Incident_Rate','Recovered','Active','Combined_Key','Case_Fatality_Ratio','Confirmed'], axis=1)
clean_data_deaths = clean_data_deaths.dropna()
clean_data_deaths.loc[~(clean_data_deaths==0.0).all(axis=1)]
clean_data_deaths = clean_data_deaths.sort_values(by='Deaths', ascending=False)
clean_data_deaths.head(50)

           Lat       Long_    Deaths   Population
118  52.355500   -1.174300  184819.0   55977200.0
373 -23.550500  -46.633300  178840.0   45919049.0
12   46.227600    2.213700  161090.0   65273512.0
603  -0.789300  113.921300  160886.0  273523621.0
525  19.449759   76.108221  148421.0  123144223.0
479  32.427908   53.688046  144804.0   83992953.0
262 -38.416100  -63.616700  130448.0   45195777.0
321  51.919400   19.145100  118826.0   37846605.0
521 -30.559500   22.937500  102595.0   59308690.0
284  38.963700   35.243300  101492.0   84339067.0
288 -11.766533  -76.604498   96635.0   10628500.0
338 -22.906800  -43.172900   76781.0   17264943.0
296  10.450898   76.405749   71581.0   35699443.0
313  45.943200   24.966800   67650.0   19237682.0
580  12.879721  121.774017   66021.0  109581085.0
289 -18.512200  -44.555000   65075.0   21168791.0
255  47.162500   19.503300   48738.0    9660350.0
570  19.496900  -99.723300   48195.0   17427790.0
188  55.750446   37.617494   48102.0   12506468.0
220 -25.252100  -52.021500   45963.0   11433957.0
95   45.466794    9.190347   45474.0   10060574.0
280  19.432600  -99.133200   43997.0    9018645.0
423  14.058324  108.277199   43186.0   97338583.0
78   49.817500   15.473000   42375.0   10708982.0
210 -30.034600  -51.217700   41900.0   11377239.0
541  14.705180   76.166436   40310.0   67562686.0
299  42.733900   25.485800   38204.0    6948445.0
561  11.006091   78.400624   38049.0   77841267.0
129  59.960674   30.158655   37078.0    5351935.0
542  -1.831200  -78.183400   36008.0   17643060.0
26   39.074200   21.824300   34779.0   10423056.0
522  15.870032  100.992541   33902.0   69799978.0
11   35.907757  127.766922   33865.0   51269183.0
418 -12.579700  -41.700700   31441.0   14873064.0
69   51.433200    7.661600   31089.0   17932651.0
185 -33.437600  -70.650500   30804.0    7112808.0
225   4.711000  -74.072100   30043.0    7412566.0
622  23.685000   90.356300   29445.0  164689383.0
467  33.886917    9.537499   29326.0   11818618.0
31   48.790400   11.497900   28323.0   13076721.0
335  -5.498400  -39.320600   28114.0    9132078.0
191 -15.827000  -49.836200   28009.0    7018354.0
443  28.646519   77.108980   26522.0   18710922.0
22   39.399900   -8.224500   26117.0   10196707.0
539  33.223191   43.679291   25375.0   40222503.0
646  26.820553   30.802498   24809.0  102334403.0
632  26.925425   80.560982   23648.0  237882725.0
184 -27.242300  -50.218900   22693.0    7164788.0
417  -8.813700  -36.954100   22676.0    9557071.0
461 -16.290200  -63.588700   22359.0   11673029.0

In [50]:
#The mistake made here is Im rendering EACH AND EVERY covid case 
#Instead of that, create an object with long, lat and total case count.
#Hence we should only have approx 4000 json objects instead of 600 million+
#TODO: Figure out how mapbox is gonna render it



for i in range(len(clean_data_case_fatality)):
    
    longitude = clean_data_case_fatality.iloc[i]['Long_']
    latitude = clean_data_case_fatality.iloc[i]['Lat']
    data_points = int(clean_data_case_fatality.iloc[i]['Case_Fatality_Ratio'])
    
    
    for x in range(data_points):
        geometry = {
        "geometry": {
          "coordinates": [
            longitude,
            latitude
          ]
        }
      }
        geoJSONDict["features"].append(geometry)
    

json_object = json.dumps(geoJSONDict, separators=(',', ":"))
with open("../mapbox-protype2/src/data/case_fatality_ratio.json", "w") as outfile:
    outfile.write(json_object)

    
geoJSONDict = {

  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "features": []
}
    
    
    

for i in range(len(clean_data_deaths)):
    
    longitude = clean_data_deaths.iloc[i]['Long_']
    latitude = clean_data_deaths.iloc[i]['Lat']
    data_points = int(clean_data_deaths.iloc[i]['Deaths'])
    
    
    for x in range(data_points):
        geometry = {
        "geometry": {
          "coordinates": [
            longitude,
            latitude
          ]
        }
      }
        geoJSONDict["features"].append(geometry)
    

json_object = json.dumps(geoJSONDict, separators=(',', ":"))
with open("../mapbox-protype2/src/data/deaths.json", "w") as outfile:
    outfile.write(json_object)

## Creating the graphs

In [51]:
vaccination_data = pd.read_csv("vaccinations-by-manufacturer.csv")

In [52]:
vaccination_data

             location        date             vaccine  total_vaccinations
0           Argentina  2020-12-29  Oxford/AstraZeneca                   1
1           Argentina  2020-12-29   Sinopharm/Beijing                   1
2           Argentina  2020-12-29           Sputnik V               20491
3           Argentina  2020-12-30           Sputnik V               40592
4           Argentina  2020-12-31           Sputnik V               43398
...               ...         ...                 ...                 ...
57665  European Union  2023-03-21          Sanofi/GSK                4532
57666  European Union  2023-03-21   Sinopharm/Beijing             2319921
57667  European Union  2023-03-21             Sinovac                8891
57668  European Union  2023-03-21           Sputnik V             1845386
57669  European Union  2023-03-21             Valneva                9775

[57670 rows x 4 columns]

In [53]:
vaccination_data.dropna()

             location        date             vaccine  total_vaccinations
0           Argentina  2020-12-29  Oxford/AstraZeneca                   1
1           Argentina  2020-12-29   Sinopharm/Beijing                   1
2           Argentina  2020-12-29           Sputnik V               20491
3           Argentina  2020-12-30           Sputnik V               40592
4           Argentina  2020-12-31           Sputnik V               43398
...               ...         ...                 ...                 ...
57665  European Union  2023-03-21          Sanofi/GSK                4532
57666  European Union  2023-03-21   Sinopharm/Beijing             2319921
57667  European Union  2023-03-21             Sinovac                8891
57668  European Union  2023-03-21           Sputnik V             1845386
57669  European Union  2023-03-21             Valneva                9775

[57670 rows x 4 columns]

In [54]:
vaccination_data.drop(['location','date'],axis=1)

                  vaccine  total_vaccinations
0      Oxford/AstraZeneca                   1
1       Sinopharm/Beijing                   1
2               Sputnik V               20491
3               Sputnik V               40592
4               Sputnik V               43398
...                   ...                 ...
57665          Sanofi/GSK                4532
57666   Sinopharm/Beijing             2319921
57667             Sinovac                8891
57668           Sputnik V             1845386
57669             Valneva                9775

[57670 rows x 2 columns]

In [55]:
vaccines_list = vaccination_data.vaccine.unique().tolist()
vaccine_dict = {}
for i in range(len(vaccines_list)):
    vaccine_dict[vaccines_list[i]] = 0
vaccine_dict

{'Oxford/AstraZeneca': 0,
 'Sinopharm/Beijing': 0,
 'Sputnik V': 0,
 'Pfizer/BioNTech': 0,
 'Moderna': 0,
 'CanSino': 0,
 'Sputnik Light': 0,
 'Johnson&Johnson': 0,
 'Novavax': 0,
 'Sanofi/GSK': 0,
 'Valneva': 0,
 'Medicago': 0,
 'Sinovac': 0,
 'Covaxin': 0,
 'SKYCovione': 0}

In [56]:
vaccine_dict = {'Oxford/AstraZeneca': 0,
 'Sinopharm/Beijing': 0,
 'Pfizer/BioNTech': 0,
 'Moderna': 0,
 'Johnson&Johnson': 0,
 'Others':0}
vaccine_dict

{'Oxford/AstraZeneca': 0,
 'Sinopharm/Beijing': 0,
 'Pfizer/BioNTech': 0,
 'Moderna': 0,
 'Johnson&Johnson': 0,
 'Others': 0}

In [57]:
for i in range(len(vaccination_data)):
    currVaccine = vaccination_data.iloc[i]['vaccine']
    currCount = vaccination_data.iloc[i]['total_vaccinations']
    
    if currVaccine == 'Oxford/AstraZeneca' or currVaccine == 'Sinopharm/Beijing' or currVaccine == 'Pfizer/BioNTech' or currVaccine == 'Moderna' or currVaccine == 'Johnson&Johnson' :
        dictCount = vaccine_dict[currVaccine]
        vaccine_dict[currVaccine] = int(currCount + dictCount)
    else:
        othersCount = vaccine_dict['Others']
        vaccine_dict['Others'] = int(currCount + dictCount)

In [58]:
vaccine_dict

{'Oxford/AstraZeneca': 82093563042,
 'Sinopharm/Beijing': 31021031484,
 'Pfizer/BioNTech': 939904167926,
 'Moderna': 263357674637,
 'Johnson&Johnson': 26013600382,
 'Others': 31018721338}

In [59]:
json_object = json.dumps(vaccine_dict, separators=(',', ":"))
with open("../mapbox-protype2/src/data/vaccines.json", "w") as outfile:
    outfile.write(json_object)

In [66]:
from datetime import date

totalCases = int(data["Confirmed"].sum())
totalDeaths = int(data["Deaths"].sum())
statsDict ={
    'totalCases': f"{totalCases:,}",
    'totalDeaths':f"{totalDeaths:,}",
    'cases_per_1000':int((totalCases/data["Population"].sum())*1000),
    'lastUpdated': date.today().strftime("%d/%m/%Y")
}
statsDict

{'totalCases': '570,920,151',
 'totalDeaths': '5,745,235',
 'cases_per_1000': 77,
 'lastUpdated': '25/03/2023'}

In [67]:
json_object = json.dumps(statsDict, separators=(',', ":"))
with open("../mapbox-protype2/src/data/stats.json", "w") as outfile:
    outfile.write(json_object)

In [73]:
data['Cases_per_1000'].sum()

136448.18359682788