In [115]:
import sys
assert sys.version_info >= (3, 5)
# Python â‰¥3.5 is required
import sklearn
assert sklearn.__version__ >= "0.20"
import numpy as np
import os
import tarfile
import urllib
import pandas as pd
import urllib.request
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve
from sklearn import preprocessing
from sklearn import metrics
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import json
from pathlib import Path

In [116]:
data = pd.read_csv("02-19-2023.csv")

In [117]:
geoJSONDict = {

  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "features": []
}

In [118]:
# incident rate = (Cases/population)*100,000
# population = (Cases*100,000)/incident rate
us_data = data.loc[data['Country_Region']=='US']
data = data[data['Country_Region']!='US']
data["Population"] = (data["Confirmed"] * 100000)/data["Incident_Rate"]
data["Case_Fatality_Ratio"] = (data["Case_Fatality_Ratio"]*100).round()
data.head(50)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Population
0,NaN,NaN,NaN,Afghanistan,2023-02-20 04:21:05,33.939110,67.709953,209107,7896,NaN,NaN,Afghanistan,537.158776,378.0,38928341.0
1,NaN,NaN,NaN,Albania,2023-02-20 04:21:05,41.153300,20.168300,334314,3596,NaN,NaN,Albania,11616.999097,108.0,2877800.0
2,NaN,NaN,NaN,Algeria,2023-02-20 04:21:05,28.033900,1.659600,271425,6881,NaN,NaN,Algeria,618.970454,254.0,43851043.0
3,NaN,NaN,NaN,Andorra,2023-02-20 04:21:05,42.506300,1.521800,47866,165,NaN,NaN,Andorra,61950.430337,34.0,77265.0
4,NaN,NaN,NaN,Angola,2023-02-20 04:21:05,-11.202700,17.873900,105184,1931,NaN,NaN,Angola,320.036336,184.0,32866268.0
5,NaN,NaN,NaN,Antarctica,2023-02-20 04:21:05,-71.949900,23.347000,11,0,NaN,NaN,Antarctica,NaN,0.0,NaN
6,NaN,NaN,NaN,Antigua and Barbuda,2023-02-20 04:21:05,17.060800,-61.796400,9106,146,NaN,NaN,Antigua and Barbuda,9298.668409,160.0,97928.0
7,NaN,NaN,NaN,Argentina,2023-02-20 04:21:05,-38.416100,-63.616700,10042136,130448,NaN,NaN,Argentina,22219.190966,130.0,45195777.0
8,NaN,NaN,NaN,Armenia,2023-02-20 04:21:05,40.069100,45.038200,446332,8719,NaN,NaN,Armenia,15062.327174,195.0,2963234.0
9,NaN,NaN,Australian Capital Territory,Australia,2023-02-20 04:21:05,-35.473500,149.012400,231529,224,NaN,NaN,"Australian Capital Territory, Australia",54082.924550,10.0,428100.0
10,NaN,NaN,New South Wales,Australia,2023-02-20 04:21:05,-33.868800,151.209300,3894431,6417,NaN,NaN,"New South Wales, Australia",47972.788864,16.0,8118000.0
11,NaN,NaN,Northern Territory,Australia,2023-02-20 04:21:05,-12.463400,130.845600,104825,90,NaN,NaN,"Northern Territory, Australia",42681.188925,9.0,245600.0
12,NaN,NaN,Queensland,Australia,2023-02-20 04:21:05,-27.469800,153.025100,1793145,2734,NaN,NaN,"Queensland, Australia",35053.171733,15.0,5115500.0
13,NaN,NaN,South Australia,Australia,2023-02-20 04:21:05,-34.928500,138.600700,878436,1322,NaN,NaN,"South Australia, Australia",50010.589240,15.0,1756500.0
14,NaN,NaN,Tasmania,Australia,2023-02-20 04:21:05,-42.882100,147.327200,285299,250,NaN,NaN,"Tasmania, Australia",53277.124183,9.0,535500.0
15,NaN,NaN,Victoria,Australia,2023-02-20 04:21:05,-37.813600,144.963100,2871225,7286,NaN,NaN,"Victoria, Australia",43307.214287,25.0,6629900.0
16,NaN,NaN,Western Australia,Australia,2023-02-20 04:21:05,-31.950500,115.860500,1288808,942,NaN,NaN,"Western Australia, Australia",48992.929370,7.0,2630600.0
17,NaN,NaN,NaN,Austria,2023-02-20 04:21:05,47.516200,14.550100,5863481,21820,NaN,NaN,Austria,65103.493072,37.0,9006400.0
18,NaN,NaN,NaN,Azerbaijan,2023-02-20 04:21:05,40.143100,47.576900,828352,10103,NaN,NaN,Azerbaijan,8169.816578,122.0,10139175.0
19,NaN,NaN,NaN,Bahamas,2023-02-20 04:21:05,25.025885,-78.035889,37491,833,NaN,NaN,Bahamas,9533.678493,222.0,393248.0
20,NaN,NaN,NaN,Bahrain,2023-02-20 04:21:05,26.027500,50.550000,704491,1548,NaN,NaN,Bahrain,41402.094403,22.0,1701583.0
21,NaN,NaN,NaN,Bangladesh,2023-02-20 04:21:05,23.685000,90.356300,2037738,29445,NaN,NaN,Bangladesh,1237.322020,144.0,164689383.0
22,NaN,NaN,NaN,Barbados,2023-02-20 04:21:05,13.193900,-59.543200,106434,573,NaN,NaN,Barbados,37037.140143,54.0,287371.0
23,NaN,NaN,NaN,Belarus,2023-02-20 04:21:05,53.709800,27.953400,994037,7118,NaN,NaN,Belarus,10519.665910,72.0,9449321.0
24,NaN,NaN,Antwerp,Belgium,2023-02-20 04:21:05,51.219500,4.402400,760234,0,NaN,NaN,"Antwerp, Belgium",40917.100559,0.0,1857986.0
25,NaN,NaN,Brussels,Belgium,2023-02-20 04:21:05,50.850300,4.351700,504172,0,NaN,NaN,"Brussels, Belgium",41717.375151,0.0,1208542.0
26,NaN,NaN,East Flanders,Belgium,2023-02-20 04:21:05,51.036200,3.737300,639119,0,NaN,NaN,"East Flanders, Belgium",42184.290565,0.0,1515064.0
27,NaN,NaN,Flemish Brabant,Belgium,2023-02-20 04:21:05,50.916700,4.583300,461298,0,NaN,NaN,"Flemish Brabant, Belgium",40246.733701,0.0,1146175.0
28,NaN,NaN,Hainaut,Belgium,2023-02-20 04:21:05,50.525700,4.062100,517106,0,NaN,NaN,"Hainaut, Belgium",38468.250857,0.0,1344241.0
29,NaN,NaN,Liege,Belgium,2023-02-20 04:21:05,50.449600,5.849200,417455,0,NaN,NaN,"Liege, Belgium",37710.751297,0.0,1106992.0
30,NaN,NaN,Limburg,Belgium,2023-02-20 04:21:05,50.973900,5.342000,348771,0,NaN,NaN,"Limburg, Belgium",39902.957275,0.0,874048.0
31,NaN,NaN,Luxembourg,Belgium,2023-02-20 04:21:05,50.054700,5.467700,122515,0,NaN,NaN,"Luxembourg, Belgium",43042.390686,0.0,284638.0
32,NaN,NaN,Namur,Belgium,2023-02-20 04:21:05,50.331000,4.822100,202090,0,NaN,NaN,"Namur, Belgium",40882.010823,0.0,494325.0
33,NaN,NaN,Unknown,Belgium,2023-02-20 04:21:05,NaN,NaN,63090,33663,NaN,NaN,"Unknown, Belgium",NaN,5336.0,NaN
34,NaN,NaN,Walloon Brabant,Belgium,2023-02-20 04:21:05,50.400000,4.350000,173221,0,NaN,NaN,"Walloon Brabant, Belgium",42919.085528,0.0,403599.0
35,NaN,NaN,West Flanders,Belgium,2023-02-20 04:21:05,51.053600,3.145800,499202,0,NaN,NaN,"West Flanders, Belgium",41746.418285,0.0,1195796.0
36,NaN,NaN,NaN,Belize,2023-02-20 04:21:05,17.189900,-88.497600,70721,688,NaN,NaN,Belize,17786.032428,97.0,397621.0
37,NaN,NaN,NaN,Benin,2023-02-20 04:21:05,9.307700,2.315800,27990,163,NaN,NaN,Benin,230.879674,58.0,12123198.0
38,NaN,NaN,NaN,Bhutan,2023-02-20 04:21:05,27.514200,90.433600,62611,21,NaN,NaN,Bhutan,8114.311338,3.0,771612.0
39,NaN,NaN,NaN,Bolivia,2023-02-20 04:21:05,-16.290200,-63.588700,1191892,22359,NaN,NaN,Bolivia,10210.648838,188.0,11673029.0
40,NaN,NaN,NaN,Bosnia and Herzegovina,2023-02-20 04:21:05,43.915900,17.679100,401527,16267,NaN,NaN,Bosnia and Herzegovina,12238.635827,405.0,3280815.0
41,NaN,NaN,NaN,Botswana,2023-02-20 04:21:05,-22.328500,24.684900,329595,2801,NaN,NaN,Botswana,14015.627492,85.0,2351625.0
42,NaN,NaN,Acre,Brazil,2023-02-20 04:21:05,-9.023800,-70.812000,160328,2043,NaN,NaN,"Acre, Brazil",18179.117509,127.0,881935.0
43,NaN,NaN,Alagoas,Brazil,2023-02-20 04:21:05,-9.571300,-36.782000,337317,7242,NaN,NaN,"Alagoas, Brazil",10107.309467,215.0,3337357.0
44,NaN,NaN,Amapa,Brazil,2023-02-20 04:21:05,0.902000,-52.003000,185025,2167,NaN,NaN,"Amapa, Brazil",21877.523704,117.0,845731.0
45,NaN,NaN,Amazonas,Brazil,2023-02-20 04:21:05,-3.416800,-65.856100,627508,14425,NaN,NaN,"Amazonas, Brazil",15140.386387,230.0,4144597.0
46,NaN,NaN,Bahia,Brazil,2023-02-20 04:21:05,-12.579700,-41.700700,1790221,31441,NaN,NaN,"Bahia, Brazil",12036.665747,176.0,14873064.0
47,NaN,NaN,Ceara,Brazil,2023-02-20 04:21:05,-5.498400,-39.320600,1451614,28114,NaN,NaN,"Ceara, Brazil",15895.768740,194.0,9132078.0
48,NaN,NaN,Distrito Federal,Brazil,2023-02-20 04:21:05,-15.799800,-47.864500,896057,11843,NaN,NaN,"Distrito Federal, Brazil",29717.325292,132.0,3015268.0
49,NaN,NaN,Espirito Santo,Brazil,2023-02-20 04:21:05,-19.183400,-40.308900,1321526,15037,NaN,NaN,"Espirito Santo, Brazil",32884.824506,114.0,4018650.0

In [119]:
us_data

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
678,1001.0,Autauga,Alabama,US,2023-02-20 04:21:05,32.539527,-86.644082,19686,230,NaN,NaN,"Autauga, Alabama, US",35235.998496,1.168343
679,1003.0,Baldwin,Alabama,US,2023-02-20 04:21:05,30.727750,-87.722071,69521,724,NaN,NaN,"Baldwin, Alabama, US",31142.657480,1.041412
680,1005.0,Barbour,Alabama,US,2023-02-20 04:21:05,31.868263,-85.387129,7431,103,NaN,NaN,"Barbour, Alabama, US",30102.082152,1.386085
681,1007.0,Bibb,Alabama,US,2023-02-20 04:21:05,32.996421,-87.125115,8049,109,NaN,NaN,"Bibb, Alabama, US",35942.663213,1.354205
682,1009.0,Blount,Alabama,US,2023-02-20 04:21:05,33.982109,-86.567906,18554,261,NaN,NaN,"Blount, Alabama, US",32085.912911,1.406705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3952,56039.0,Teton,Wyoming,US,2023-02-20 04:21:05,43.935225,-110.589080,12113,16,NaN,NaN,"Teton, Wyoming, US",51623.764064,0.132089
3953,56041.0,Uinta,Wyoming,US,2023-02-20 04:21:05,41.287818,-110.547578,6373,43,NaN,NaN,"Uinta, Wyoming, US",31508.948878,0.674721
3954,90056.0,Unassigned,Wyoming,US,2023-01-08 23:21:00,NaN,NaN,0,0,NaN,NaN,"Unassigned, Wyoming, US",NaN,NaN
3955,56043.0,Washakie,Wyoming,US,2023-02-20 04:21:05,43.904516,-107.680187,2744,50,NaN,NaN,"Washakie, Wyoming, US",35156.950673,1.822157
3956,56045.0,Weston,Wyoming,US,2023-02-20 04:21:05,43.839612,-104.567488,1897,23,NaN,NaN,"Weston, Wyoming, US",27385.592609,1.212441

In [120]:
#data struct to store states
# for every state in us_data: 
# get average of Case_Fatality_Ratio, median of lat and long, country
# insert row into data

states =  us_data.Province_State.values.tolist()
states = list(dict.fromkeys(states))

for state in states:
    tempDf = us_data.loc[us_data['Province_State']==state]
    stateDf = tempDf.groupby('Province_State', as_index=False).Case_Fatality_Ratio.max()
    lat = tempDf.groupby('Province_State', as_index=False).Lat.median().iloc[0]['Lat']
    long = tempDf.groupby('Province_State', as_index=False).Long_.median().iloc[0]['Long_']
    country = "US"
    stateDf["Lat"] = lat
    stateDf["Long_"] = long
    stateDf["Country_Region"] = country
    stateDf
    data = data.append(stateDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)

C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)
C:\Users\Shawn\AppData\Local\Temp\ipykernel_20736\1243832962.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(stateDf, ignore_index=True)

In [121]:
sampleDf = data.loc[data['Country_Region']=='US']
sampleDf

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Population
737,NaN,NaN,Alabama,US,NaN,32.855042,-86.662326,NaN,NaN,NaN,NaN,NaN,NaN,2.388060,NaN
738,NaN,NaN,Alaska,US,NaN,60.067639,-149.953805,NaN,NaN,NaN,NaN,NaN,NaN,0.867679,NaN
739,NaN,NaN,American Samoa,US,NaN,-14.271000,-170.132000,NaN,NaN,NaN,NaN,NaN,NaN,0.408654,NaN
740,NaN,NaN,Arizona,US,NaN,33.348359,-111.344948,NaN,NaN,NaN,NaN,NaN,NaN,2.663969,NaN
741,NaN,NaN,Arkansas,US,NaN,35.002924,-92.499744,NaN,NaN,NaN,NaN,NaN,NaN,3.789593,NaN
742,NaN,NaN,California,US,NaN,38.048832,-120.918298,NaN,NaN,NaN,NaN,NaN,NaN,1.545284,NaN
743,NaN,NaN,Colorado,US,NaN,38.934415,-105.451273,NaN,NaN,NaN,NaN,NaN,NaN,8.984375,NaN
744,NaN,NaN,Connecticut,US,NaN,41.641359,-72.634094,NaN,NaN,NaN,NaN,NaN,NaN,1.462510,NaN
745,NaN,NaN,Delaware,US,NaN,39.086466,-75.568849,NaN,NaN,NaN,NaN,NaN,NaN,1.268488,NaN
746,NaN,NaN,Diamond Princess,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
747,NaN,NaN,District of Columbia,US,NaN,38.904178,-77.016560,NaN,NaN,NaN,NaN,NaN,NaN,0.804672,NaN
748,NaN,NaN,Florida,US,NaN,29.459336,-82.318310,NaN,NaN,NaN,NaN,NaN,NaN,64.578899,NaN
749,NaN,NaN,Georgia,US,NaN,32.749765,-83.688450,NaN,NaN,NaN,NaN,NaN,NaN,4.695562,NaN
750,NaN,NaN,Grand Princess,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.912621,NaN
751,NaN,NaN,Guam,US,NaN,13.444300,144.793700,NaN,NaN,NaN,NaN,NaN,NaN,0.685887,NaN
752,NaN,NaN,Hawaii,US,NaN,21.161014,-157.270064,NaN,NaN,NaN,NaN,NaN,NaN,0.551900,NaN
753,NaN,NaN,Idaho,US,NaN,43.767223,-114.737564,NaN,NaN,NaN,NaN,NaN,NaN,2.864259,NaN
754,NaN,NaN,Illinois,US,NaN,39.814165,-89.145852,NaN,NaN,NaN,NaN,NaN,NaN,7750.769231,NaN
755,NaN,NaN,Indiana,US,NaN,39.802341,-86.183476,NaN,NaN,NaN,NaN,NaN,NaN,2.609189,NaN
756,NaN,NaN,Iowa,US,NaN,42.036571,-93.464990,NaN,NaN,NaN,NaN,NaN,NaN,3.191489,NaN
757,NaN,NaN,Kansas,US,NaN,38.481194,-98.086073,NaN,NaN,NaN,NaN,NaN,NaN,3.296703,NaN
758,NaN,NaN,Kentucky,US,NaN,37.579299,-84.869131,NaN,NaN,NaN,NaN,NaN,NaN,2.846648,NaN
759,NaN,NaN,Louisiana,US,NaN,30.833178,-91.785282,NaN,NaN,NaN,NaN,NaN,NaN,2.339181,NaN
760,NaN,NaN,Maine,US,NaN,44.492680,-69.654828,NaN,NaN,NaN,NaN,NaN,NaN,1.264711,NaN
761,NaN,NaN,Maryland,US,NaN,39.099376,-76.604793,NaN,NaN,NaN,NaN,NaN,NaN,2.009156,NaN
762,NaN,NaN,Massachusetts,US,NaN,42.327951,-71.205304,NaN,NaN,NaN,NaN,NaN,NaN,1.561453,NaN
763,NaN,NaN,Michigan,US,NaN,43.987942,-85.049805,NaN,NaN,NaN,NaN,NaN,NaN,4.062500,NaN
764,NaN,NaN,Minnesota,US,NaN,45.274760,-94.528395,NaN,NaN,NaN,NaN,NaN,NaN,46.230599,NaN
765,NaN,NaN,Mississippi,US,NaN,32.766767,-89.545897,NaN,NaN,NaN,NaN,NaN,NaN,2.931596,NaN
766,NaN,NaN,Missouri,US,NaN,38.428825,-92.572150,NaN,NaN,NaN,NaN,NaN,NaN,3.251232,NaN
767,NaN,NaN,Montana,US,NaN,46.998269,-110.027747,NaN,NaN,NaN,NaN,NaN,NaN,3.265306,NaN
768,NaN,NaN,Nebraska,US,NaN,41.227810,-98.527989,NaN,NaN,NaN,NaN,NaN,NaN,5.309735,NaN
769,NaN,NaN,Nevada,US,NaN,39.441570,-118.110943,NaN,NaN,NaN,NaN,NaN,NaN,7.142857,NaN
770,NaN,NaN,New Hampshire,US,NaN,43.328785,-71.549000,NaN,NaN,NaN,NaN,NaN,NaN,1.612515,NaN
771,NaN,NaN,New Jersey,US,NaN,40.436299,-74.658485,NaN,NaN,NaN,NaN,NaN,NaN,1.525754,NaN
772,NaN,NaN,New Mexico,US,NaN,34.716698,-105.850895,NaN,NaN,NaN,NaN,NaN,NaN,4.339623,NaN
773,NaN,NaN,New York,US,NaN,42.634990,-74.999304,NaN,NaN,NaN,NaN,NaN,NaN,1.573392,NaN
774,NaN,NaN,North Carolina,US,NaN,35.663659,-79.294474,NaN,NaN,NaN,NaN,NaN,NaN,2.001202,NaN
775,NaN,NaN,North Dakota,US,NaN,47.453678,-99.964078,NaN,NaN,NaN,NaN,NaN,NaN,2.572347,NaN
776,NaN,NaN,Northern Mariana Islands,US,NaN,15.097900,145.673900,NaN,NaN,NaN,NaN,NaN,NaN,0.301360,NaN
777,NaN,NaN,Ohio,US,NaN,40.358888,-82.996822,NaN,NaN,NaN,NaN,NaN,NaN,3.297083,NaN
778,NaN,NaN,Oklahoma,US,NaN,35.542606,-97.144214,NaN,NaN,NaN,NaN,NaN,NaN,1429.605263,NaN
779,NaN,NaN,Oregon,US,NaN,44.718069,-121.936583,NaN,NaN,NaN,NaN,NaN,NaN,2.134146,NaN
780,NaN,NaN,Pennsylvania,US,NaN,40.816656,-77.399751,NaN,NaN,NaN,NaN,NaN,NaN,3.360756,NaN
781,NaN,NaN,Puerto Rico,US,NaN,18.251719,-66.348695,NaN,NaN,NaN,NaN,NaN,NaN,21.927958,NaN
782,NaN,NaN,Recovered,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783,NaN,NaN,Rhode Island,US,NaN,41.671063,-71.576416,NaN,NaN,NaN,NaN,NaN,NaN,1.083644,NaN
784,NaN,NaN,South Carolina,US,NaN,34.020765,-81.040737,NaN,NaN,NaN,NaN,NaN,NaN,2.032735,NaN
785,NaN,NaN,South Dakota,US,NaN,44.184784,-99.042527,NaN,NaN,NaN,NaN,NaN,NaN,4.140787,NaN
786,NaN,NaN,Tennessee,US,NaN,35.929299,-86.057390,NaN,NaN,NaN,NaN,NaN,NaN,2.227171,NaN
787,NaN,NaN,Texas,US,NaN,31.783209,-98.543035,NaN,NaN,NaN,NaN,NaN,NaN,6.147809,NaN
788,NaN,NaN,Utah,US,NaN,40.331102,-111.575868,NaN,NaN,NaN,NaN,NaN,NaN,1.040031,NaN
789,NaN,NaN,Vermont,US,NaN,44.368330,-72.678128,NaN,NaN,NaN,NaN,NaN,NaN,0.770934,NaN
790,NaN,NaN,Virgin Islands,US,NaN,18.335800,-64.896300,NaN,NaN,NaN,NaN,NaN,NaN,0.526209,NaN
791,NaN,NaN,Virginia,US,NaN,37.375699,-78.173251,NaN,NaN,NaN,NaN,NaN,NaN,3.454545,NaN
792,NaN,NaN,Washington,US,NaN,47.140037,-120.791360,NaN,NaN,NaN,NaN,NaN,NaN,2.409639,NaN
793,NaN,NaN,West Virginia,US,NaN,38.892851,-80.706715,NaN,NaN,NaN,NaN,NaN,NaN,1.991885,NaN
794,NaN,NaN,Wisconsin,US,NaN,44.434222,-89.668273,NaN,NaN,NaN,NaN,NaN,NaN,2.773156,NaN
795,NaN,NaN,Wyoming,US,NaN,43.041840,-106.886239,NaN,NaN,NaN,NaN,NaN,NaN,2.148438,NaN

In [122]:
clean_data = data.drop(['FIPS', 'Admin2','Province_State','Country_Region','Last_Update','Deaths','Recovered','Active','Combined_Key','Incident_Rate','Confirmed','Population'], axis=1)
clean_data = clean_data.dropna()
clean_data.loc[~(clean_data==0.0).all(axis=1)]

           Lat       Long_  Case_Fatality_Ratio
0    33.939110   67.709953           378.000000
1    41.153300   20.168300           108.000000
2    28.033900    1.659600           254.000000
3    42.506300    1.521800            34.000000
4   -11.202700   17.873900           184.000000
..         ...         ...                  ...
791  37.375699  -78.173251             3.454545
792  47.140037 -120.791360             2.409639
793  38.892851  -80.706715             1.991885
794  44.434222  -89.668273             2.773156
795  43.041840 -106.886239             2.148438

[772 rows x 3 columns]

In [123]:
clean_data["Case_Fatality_Ratio"].sum()

174765.6397587355

In [124]:
#The mistake made here is Im rendering EACH AND EVERY covid case 
#Instead of that, create an object with long, lat and total case count.
#Hence we should only have approx 4000 json objects instead of 600 million+
#TODO: Figure out how mapbox is gonna render it



for i in range(len(clean_data)):
    
    longitude = clean_data.iloc[i]['Long_']
    latitude = clean_data.iloc[i]['Lat']
    data_points = int(clean_data.iloc[i]['Case_Fatality_Ratio'])
    
    
    for x in range(data_points):
        geometry = {
        "geometry": {
          "coordinates": [
            longitude,
            latitude
          ]
        }
      }
        geoJSONDict["features"].append(geometry)
    

json_object = json.dumps(geoJSONDict, separators=(',', ":"))
with open("../server/case_fatality_ratio.json", "w") as outfile:
    outfile.write(json_object)

In [ ]:
csv_total